export const TABLE_NAMES = {
  USER: '"user"',
  HASH_CONFIG: "hash_config",
  USER_HASH_BRIDGE: "user_hash",
  ROOM: "room",
  XTREAM_CONFIGS: "xtream_configs",
  DIRECT_CONFIGS: "direct_configs",
  LIVE_STREAM: "live_stream",
  MOVIE_STREAM: "movie_stream",
  SERIES_STREAM: "series_stream",
  LIVE_CATEGORY: "live_category",
  MOVIE_CATEGORY: "movie_category",
  SERIES_CATEGORY: "series_category",
  SCHEDULER: "scheduler",
  FETCH_TIMING: "fetch_timing",
  STREAM_EVENT_RESUME: "stream_event_resume",
  ROOM_LOG_LINE: "room_log_line",
  STREAM_FETCH_STATUS: "stream_fetch_status",
  SERIES_EPISODE: "series_episode",
  STREAM_PROXY_STATE: "stream_proxy_state",
};
